### ISSUE TITLE
Invalid receiver: "'m"

### ISSUE THREAD

**Issue by hedisam** [ricardoerikson/vscode-go-impl-methods#3]
Hi Recardo

The plugin doesn't work even with the provided example by yourself.

Here's what I do:

```golang
type myStruct struct {}

// m myStruct
```

The error is as the title: Invalid receiver: "'m".
Note the single quote before the receiver's name in the error message

Thanks

**Comment by ricardoerikson** [comment]
Hi @hedisam. Thank you for reporting the issue. Are you using Windows? I noticed this happens especially on Windows systems because of this single quote. I'm pushing a fix for this and releasing a new version. Let me know if you still have a problem with the new release.

**Comment by hedisam** [comment]
Hi @ricardoerikson, thanks for your reply. 
Yes, I'm on Windows.
I'll check it out later for sure.
Thanks.

**Comment by hedisam** [comment]
Hi again @ricardoerikson,
Looks like it works with Go defined interfaces (e.g. io.Reader) but it doesn't with user-defined ones. 
It shows the error `unrecognized interface: MyInterface` with `MyInterface` being the interface that I want to implement. 
Also, it shows the message `Generating stub methods...` and gets stuck on it.

**Comment by ricardoerikson** [comment]
Hey @hedisam, I just pushed a fix for when it gets stuck on the message `Generating stub methods...`. Now, can you explain what you are trying to generate and how you are doing that? I did some tests with user-defined interfaces on a Windows machine, and it's working fine.

**Comment by hedisam** [comment]
I got your update, the `Generating stub methods...` problem is fixed now, but It still can't recognize user-defined interfaces.
Here's an example of what I'm trying to do:
```golang
package main 

type Hello interface {
    Hi(string) string 
}

type myHi struct {}

// h myHi 
```

**Comment by ricardoerikson** [comment]
That's weird. It's working fine here. A few things you can try are:
- to prefix your interface name with the package name if you have a package (like `mypkg.Hello`) 
- see if you can generate the stubs from your terminal by typing the receiver and interface name. This extension uses the [impl](https://github.com/josharian/impl) lib to generate the stubs. You can do like this:

```
impl "h myHi" Hello
```

I did this using PowerShell and I got the following result:
```go
func (h myHi) Hi(_ string) string {
        panic("not implemented") // TODO: Implement
}
```

If you can not get the method stubs by using `impl` that means the problem may be related to your `impl` installation.

**Comment by hedisam** [comment]
None of them worked until I manually updated and installed the `impl` package. You were right, it was because of the `impl` installation.
The problem is resolved now, thanks @ricardoerikson
